- name: "Copy BashRC"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"
    backup: yes

- name: Install tmux
  package:
    name:
      - tmux
  become: true
  become_method: sudo

- name: Install tpm
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.local/share/tmux/plugins/tpm"
    depth: 1

- name: Copy tmux custom config
  copy:
    src: "{{ role_path }}/files/tmux"
    dest: ~/.config
